name: Go

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o jdd cmd/main.go

    - name: Generate Dockerfile
      run: |
        echo 'FROM ubuntu:focal' >> Dockerfile
        echo 'WORKDIR /app' >> Dockerfile
        echo 'COPY ./craw.sh .' >> Dockerfile
        echo 'RUN chmod +x ./craw.sh' >> Dockerfile
        echo 'COPY ./jdd .' >> Dockerfile
        echo 'CMD ["./jdd"]' >> Dockerfile

    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get the version
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        if [[ ${GITHUB_REF} == "refs/heads/master" ]]; then
          VERSION=latest
        fi
        echo ::set-output name=VERSION::${VERSION}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.7.0
      with:
        push: true
        tags: majian159/java-debug-daemon:${{ steps.get_version.outputs.VERSION }}
        context: .
